mbasso/awesome-wasm

README.md
The included link is to a WebAssembly demo I did for my YouTube channel about a month ago - it demos a 3D skeletal animation system that has been implemented in both WebAssembly (compiled from C++) and vanilla JavaScript. It shows the performance difference between naive implementations of a CPU-intensive task in both environments, and provides a link to a live demo. The video itself doesn't provide meaningful contributions to this list (the resources listed are more than sufficient) but I think the demo would be worthwhile to put here.
There is another really good project/demo at https://github.com/shamadee/web-dsp that serves a very similar purpose. I would be more than glad to modify this PR to include that one as well, or put up another PR.
Thanks for putting together this list - it's …
=> Add JS vs. WASM demo - skeletal animation (3D/WebGL)

README.md
=> add MXnet.js

README.md
This is an in-depth introduction to WebAssembly (binary format, text
format, rationale, operations, memory management, JS API, etc):
https://rsms.me/wasm-intro
=> Add rsms.me intro article.

README.md
https://webassembly.github.io/spec/
A related pull request: https://github.com/WebAssembly/spec/pull/467
=> Add WebAssembly Specification link

README.md
Add [Asmble](https://github.com/cretz/asmble) project
=> Add Asmble Project

README.md
Hi, I've created a document translated to Chinese from [official repo](https://github.com/WebAssembly/website), it's still in process, and i think it's appropriate adding to this list, thanks :-)
> [Repo site](https://github.com/int64ago/wasm-cn)
=> Add document in Chinese

README.md
=> Add a paper section.

README.md
https://fossil.e-lehmann.de/wacl/index
=> Add wacl (Tcl interpreter in WASM) and wasmachine (wasm on FPGA)

README.md
=> Added Demo: Symatem

README.md
=> Add 'wasm.news' website

README.md
Useful examples for creating zero-overhead WASM using C.
=> Added wasm-intro

README.md
Original description is 'Super charged JavaScript / TypeScript for parallel programming which compiles to asm.js and WebAssembly', so I shortened it a bit. See: https://github.com/01alchemist/TurboScript
=> Added TurboScript

README.md
=> Add project rusty web

README.md
=> Add EpicZenGarden Demo

README.md
- [Meeting C++ 2016: Implementing a web game in C++14 - Kris Jusiak (2016)](https://www.youtube.com/watch?v=8gRHHIjx4oE)
- [CppCon 2016: Dan Gohman “C++ on the Web: Let's have some serious fun." (2016)](https://www.youtube.com/watch?v=jXMtQ2fTl4c)
- [NYLUG Presents: Luke Wagner -on- WebAssembly: A New Compiler Target For The Web (2016)](https://www.youtube.com/watch?v=RByPdCN1RQ4)
=> Add videos by Luke Wagner, Dan Groham & Kris Jusiak

README.md
=> Add emscripten html integration tips

README.md
=> Add yet another WebAssembly script languages

README.md
Hello,
I would like to submit my demo for consideration in your list.
Thanks!
=> Demos : add Funky Karts

README.md
=> Add my talk at KharkivJS (ru)

README.md
Hi, currently starting with WebAssembly, I went through your list but still had to spend two days to get a simple C code working in wasm and have it integrate smoothly with the js client code. I encountered some tough roadblocks on the way but eventually mangaged to get past them.
I made a tutorial from this experience in the hope that an up-to-date article could help others get started as I did: http://blog.openbloc.fr/webassembly-first-steps/
=> Added a tutorial link

README.md
Repository: https://github.com/fiatjaf/jq-web
Demo: https://fiatjaf.alhur.es/jq-web/
original jq: https://stedolan.github.io/jq/manual/
=> add jq-web

README.md
=> Add rust2wasm tutorial

README.md
We built a Chinese WebAssembly online group. Do some thing about WebAssembly.
=> Add some Chinese website and a Orgnization.

README.md
=> Mention parity-wasm

README.md
A community for developers looking to put WebAssembly to use today.
=> Added WebAssembly Rocks

README.md
=> Add lin clark's latest webassembly articles

README.md
=> add wah language

README.md
I wrote a small collection of webassembly examples. My collection includes wast syntax, clang / llvm / emscripten build and data structures.
https://github.com/reklatsmasters/webassembly-examples
=> Add reklatsmasters/webassembly-examples

README.md
=> A few new links!

README.md
=> Updated URL for wasm weekly

README.md
=> Add cld3, hunspell-asm

README.md
=> Added Wasm2Wat to online playgrounds

README.md
Hi! We wrote a lengthy in-depth article to optimize WebAssembly performance: 4 simple yet effective solutions to reduce load time.
I read the CONTRIBUTING guide yet it seems that the Articles list is sorted from year newest -> oldest, so I added it at the top. Hope that's okay.
=> Add Optimizing WebAssembly Startup Time Article

README.md
=> [Related to issue #59] fix travis build

README.md
Here is my another resourse for webassembly - extension for vscode https://marketplace.visualstudio.com/items?itemName=dtsvet.vscode-wasm.
=> Added vscode-wasm extension.

README.md
=> Add WebAssembly Spanish Blogpost

README.md
Ha! I just saw that I forget to add some explanation about our PDF product. Would be great if you can add this. 😊
=> Add more information about PSPDFKit

README.md
Added a new webpack loader to the webpack section. (cpp-wasm-loader).
=> Added Webpack Loader cpp-wasm-loader

README.md
This commit adds the Ooui.wasm project, and adds a new Category: XAML.
Thanks !
=> Add Ooui.Wasm

README.md
https://github.com/Xe/olin https://olin-http-example.herokuapp.com
=> README: link to Olin

README.md
=> add link to wasmjit

README.md
go-vdom-wasm is an *experiment* to create a VDOM in Golang for Webassembly. It's widely inspired by https://github.com/mbasso/asm-dom but stands experimental.
You can contribute or just have fun :blush: : https://github.com/mfrachet/go-vdom-wasm
=> Adding go-vdom-wasm

README.md
Adding go-wasm-cli that is a little nodejs utilities to create and run (with hot reload thanks to https://facebook.github.io/watchman/) Go application targetting wasm.
It aims to `create` and `start` an app. nothing more 😊 
Hope this will interest you foks!
https://github.com/mfrachet/go-wasm-cli
=> Adding go-wasm-cli

README.md
=> Added ewasm

README.md
=> Update broken Faust entry url

README.md
=> update: add new resource.

README.md
=> Add entry for TinyGo

README.md
=> Typo in webpack section

README.md
=> Added WebAssembly Jobs

README.md
=> Add Kotlin/Native

README.md
=> Add warpy rpython non-web embedding

README.md
=> Add wasm-like language: wam

README.md
adds the webm-wasm project: https://github.com/GoogleChromeLabs/webm-wasm
=> add webm-wasm

README.md
This book is written by Kevin Hoffman for The Pragmatic Programmers, and is currently in beta.
=> Add Programming WebAssembly with Rust

README.md
=> Add 'The world’s easiest introduction to WebAssembly with Golang' article

README.md
=> Update AssemblyScript link. Mark other js-like compilers as unmaintained

README.md
=> Add a web framework

README.md
=> chore: add Lys lang

README.md
=> Add WASI to Non-Web Embeddings

README.md
=> Add Vugu to Web frameworks-libraries

README.md
- [ x] I've read [CONTRIBUTING.md](https://github.com/mbasso/awesome-wasm/blob/master/CONTRIBUTING.md).
- [x ] Description explains the issue / use-case resolved, and auto-closes the related issue(s) (https://help.github.com/articles/closing-issues-via-commit-messages/).
=> Add Article: Practice your Go WebAssembly with a Game

README.md
Added man page for WebAssembly
=> Added man page for WebAssembly

README.md
Added two case studies to the articles section, and two tutorials for Go and AssemblyScript respectively.
=> Add four recent articles

README.md
=> Added link to the Windows 10 calculator running in WebAssembly

README.md
This PR is to add 3 tutorials and a video talk about WebAssembly 😄
=> Adding three tutorials and a video talk

README.md
=> Add to README: Wasm vs PNaCl Performance Benchmark by PDFTron

README.md
=> Add to README: PDFTron Wasm demo (WebViewer)

README.md
Adding explanatory Video by few of the creators.
=> Adding explanatory Video by few of the creators

README.md
This project is almost written by wasm(wasm-bindgen apis)
=> Add HNPWA with WASM example

README.md
=> Updates on Rust section

README.md
=> Add a golang example

README.md
=> Added Uno Platform one-day bootcamp to the list of tutorials

README.md
=> Add wasm3, the fastest WebAssembly interpreter

README.md
This adds an awesome talk by David Beazly where he live codes a wasm interpreter in python to explain stack machines which in the end runs a game programmed in rust and compiled to web assembly.
=> Add David Beazleys talk where he is live-coding a wasm interpreter

README.md
This adds [WasmByExample](https://wasmbyexample.dev/) to the tutorial list :smile: 
Test failures appear to be on master, as they are also on #142 PR, which I am also experiencing. :hushed:
=> Added WasmByExample

README.md
This adds [Made With WebAssembly](https://madewithwebassembly.com/) to the examples list :smile: 
Test failures appear to be on master, as they are also on #142 PR, which I am also experiencing. :hushed:
=> Added Made With WebAssembly

README.md
=> Never language added to the list of languages compiled to wasm

README.md
This is a usable, however working in progress project. It shows how fast Go+Wasm can update a heavy CPU usage feature in browser, without UI lock (thanks to WebWorkers).
=> Adds WAsm Heatmap

README.md
WebAssembly beyond the browser! SSVM is a high performance, hardware optimal Wasm Virtual Machine for AI and Blockchain applications.
=> Update README.md & add SSVM

README.md
Hi! Just adding some slides for a talk I gave about Web Assembly. It's not a deep dive, meant to be an intro to WASM practical use cases for beginners or less-technical stakeholders.
Also - it seems slides are ordered chronologically, so I put it at the top of the list, is that a correct assumption? 
Thanks in advance. Great awesome list resource btw - helped me a lot.
=> feat: add an item to "slides"

README.md
I added a new tutorial about "First steps with WebAsssembly in Rust".
=> add new tutorial about "First steps with WebAsssembly in Rust"

README.md
Contrary to `CONTRIBUTING.md` I have not created a PR for each of these. I can do that, but it will take a while, given it is 9 additions.
@mbasso please kindly let me know if you'd really prefer that.
=> Add more non-web engines

README.md
Including https://evilmartians.com/chronicles/hands-on-webassembly-try-the-basics which provides a great starter introduction/tutorial for webassembly using C as well as Rust.
Provides a docker image for easy setup for beginners and also introduces various tools like emscripten, bynarien, wabt,  
Also great introduction to compilers and v8-wasm integration.
Link has not been added at the bottom of Tutorial Category, as it is date ordered. [Based on this guideline] (https://github.com/mbasso/awesome-wasm/blame/master/CONTRIBUTING.md#L18)
=> hands-on-webassembly-try-the-basics under tutorial

README.md
I added a link to the Tutorials section for the 'Using WebAssembly modules in C#' article that walks you through creating an ASP.NET Core MVC application that uses custom model validation. The JavaScript validation uses the Emscripten generated JavaScript to load and interact with the module while the C# validation uses the Wasmtime runtime for .NET.
=> Tutorial for Using WebAssembly modules in C#

README.md
=> Removed duplicate entry for pywasm

README.md
=> Fix a resource link

README.md
Adds the new `wasicaml` code generator that allows you to generate WASM code for apps written in  OCaml.
=> add wasicaml

README.md
These provide WebGL and DOM bindings for AssemblyScript applications.
=> Add LUME glas and asdom AssemblyScript projects

README.md
Wasmoon lets you build a high level Lua VM with interactive bindings on JS environment.
Repository: https://github.com/ceifa/wasmoon
=> Add wasmoon to Lua

README.md
Adding Zwitterion: https://github.com/lastmjs/zwitterion
=> Update README.md with Zwitterion

README.md
This PR adds a link to my article on WebAssembly SIMD
=> Add article about WebAssembly SIMD

README.md
PyScript is an exciting new Python project by Anaconda that helps with running Python code in the browser easier than Pyodide
https://github.com/pyscript/
=> Added PyScript

README.md
https://github.com/remko/waforth
=> Add Forth section with WAForth link

README.md
=> add gotemplate.io

README.md
=> Typo: It's Simplified Chinese instead of Simple Chinese

README.md
=> Adding WebAssembly Course

README.md
=> Add gameboy emulator in rust

README.md
<a href="https://boytacean.joao.me" target="_blank"><img src="https://github.com/joamag/boytacean/raw/master/res/videos/002-mario.low.gif" width="360" /></a>
Site: https://boytacean.joao.me
Description: https://github.com/joamag/boytacean
=> Adding Boytacean to the list

README.md
Hi maintainers,
This PR introduces an additional category: AI, under Projects. The goal is to create visibility of Rust in the field. I added a new library of mine as a start. Thanks!
=> docs: add ai category

README.md
=> Added my latest article to the list of articles.

README.md
=> add crypto-js-wasm

README.md
repo: https://github.com/extism/extism
=> add Extism to non-web embedding list

README.md
Added 2 more platform Uno targets.
=> Updated readme - Uno bullet

README.md
Tutorial on how to write programs directly in WebAssembly Text
- [* ] I've read [CONTRIBUTING.md](https://github.com/mbasso/awesome-wasm/blob/master/CONTRIBUTING.md).
- [* ] Description explains the issue / use-case resolved, and auto-closes the related issue(s) (https://help.github.com/articles/closing-issues-via-commit-messages/).
=> Add Introduction to WebAssembly Text

README.md
Adding my project: https://github.com/hullarb/ssheasy that's an online ssh,sftp client.
The wasm web client is written in golang and shows how to proxy tcp connections through
websockets.
=> Added link to ssheasy in Project/Others section.

README.md
=> Adding Apache Server mod_wasm
