mbasso/awesome-wasm

README.md

The general concept of non-web embeddings is described at
http://webassembly.org/docs/non-web/
The also adds a link to wac: https://github.com/kanaka/wac (caveat:
I am the creator of wac).

Non-Web Embeddings Section and wac project

---

README.md

Also added a new subcategory 'node.js' under 'Projects'. While it is able to compile C code to WebAssembly modules, it isn't a compiler on its own, technically, because it uses LLVM under the hood. It's actually a toolkit, so it would also fit under 'Tools', but I picked 'Projects' instead because the 'node.js' category seems to be a better fit there.
npm: https://www.npmjs.com/package/webassembly
GitHub: https://github.com/dcodeIO/WebAssembly

Added webassembly for node.js

---

README.md

This PR adds a link to the WASM / asm.js samples page of the Oryol 3D-coding framework. The github repo is here: https://github.com/floooh/oryol

Add Oryol 3D coding framework

---

README.md

This PR adds a link to the WASM version of my multi-system 8-bit emulator, the github repo is here: https://github.com/floooh/yakc

Add YAKC 8-bit emulator

---

README.md

This changeset adds to the list of compilers the announcement of WebAssembly support in the GNU toolchain (binutils, etc.)

Add GNU Toolchain to compilers list

---

README.md

Assembleash is playground for WebAssembly and Typescript-like (AssemblyScript, TurboScript and Speedy.js) languages.

add link to Assembleash Playgound

---

README.md

Adds the projects:
- [WebAssembly/wabt](https://github.com/WebAssembly/wabt)
- [mafintosh/webassembly-binary-toolkit](https://github.com/mafintosh/webassembly-binary-toolkit)
Under a new category "Toolkit"

Create category "Toolkit" and add WABT links

---

README.md

A link to the slides can be found [here](https://kgryte.github.io/talks-fullstack-london-2017-3/#/splash).  A link to the talk repository can be found [here](https://github.com/kgryte/talks-fullstack-london-2017-3).

Add WebAssembly talk at FullStack 2017

---

README.md

This post describes how PSPDFKit uses WebAssembly to build a first-class
PDF framework for the web.

Add WebAssembly post by PSPDFKit

---

README.md

cause repository moved to organization

Update repository link for parity-wasm

---

README.md

Add wat2wasm online tool from spec maintainers.

Add wat2wasm demo from wabt (the original WASM binary tookit).

---

README.md

Hi, I would like to add a link to [Walt](https://github.com/ballercat/walt) as one of the language options. 
Thanks!

Add a link to Walt, Alternative Syntax for wasm

---

README.md

According to message at Steve Sanderson's repo https://github.com/SteveSanderson/Blazor: "Moved to the ASP.NET org"

Project Blazor moved to MS

---

README.md

Add to the Examples category an example of an app based on C++/OpenGL/OpenAL/GLFW/GLM, built with CMake targeting native Linux/Macos/WIndows or WebAssembly (by means of Emscripten SDK).
This example shows how to create an application that works natively or with WebAssembly by using the same audio/video rendering engine source code.

 Add to Examples category CppOpenGLWebAssemblyCMake

---

README.md

For quite some time we have a public preview of our WebAssembly PDF engine online. It ships with all optimizations that are available today and you can even open your own PDFs (without them being sent to our servers.

Add PSPDFKit for Web Demo

---

README.md

I'm enthusiastic about WASM projects in Python and would like to list them somewhere. I considered creating a fresh new list, but I thought that riding this list might be better. What do you think?
This PR restructures the sections a bit (it does not add or remove anything) to allow more (better structured) per-language links. When this is accepted, I'll submit new links, mostly for Python-related projects.

Own section for per-lang links

---

README.md

PPCI is the Pure Python Compiler Infrastructure, an experimental compiler written in Python. It has support for WASM, and can compiler WASM to X86. PPCI supports several architectuires, so its a matter of making the backends more complete to also compile to e.g. ARM. Work in progress, but worth mentioning IMO.
Disclaimer: I am not the main author of PPCI, but have contributed to adding support for WASM.

Add PPCI compiler

---

README.md

* I alphabetically ordered the languages (should have done this in my other PR)
* Added Pyodide project (compiles CPython, Numpy, pandas and Matplotlib to wasm)
* Added Rocket game demo (disclaimer: I am the author) `*`
`*` I added a little link to PPCI in the Rocket game entry, because that demo heavily relies on it. I also think it's worth mentioning (briefly) PPCI in the "Python" section, even though its technically a compiler (which is where I added it in my other PR). Let me know if you'd like to have it another way.

Add two Python projects

---

README.md

This PR is adding a new category: XAML, as well as Uno Platform related entries and demos.
I'm also not sure about the new category position, so I added it last, above Others, and I can split for the each demos if necessary.
**Edit**: I did not place the uno playground demo in the "playgrounds" category because it seems wasm language specific. But should it ? 
Disclamer, I'm a developer on the project.
Thanks!

Add Uno Platform and demos

---

README.md

Hey! I'm wondering if my example project/article fits in here somewhere?
[WebAssembly A* Pathfinding](https://github.com/jakedeichert/wasm-astar)
If not, feel free to close! 🙂

Add wasm-astar example

---

README.md

This adds wasmtime as a non-Web wasm embedding.
The wasmtime repository is here:
https://github.com/CraneStation/wasmtime

Add wasmtime as a non-Web wasm embedding.

---

README.md

Hi there! This PR is to add a link under books to the _Level up with WebAssembly_ book at http://www.levelupwasm.com/

Adding "Level up with WebAssembly" under books

---

README.md

Adding Wasabi to the Non-Web Embeddings section. Wasabi is a WebAssembly runtime for Go (and other things).
https://github.com/maxmcd/wasabi/

Add Wasabi

---

README.md

WASM-PDF is a new project created with Rust's wasm-bindgen, hopefully someone will find it useful. https://github.com/jussiniinikoski/wasm-pdf
- [ x] I've read [CONTRIBUTING.md](https://github.com/mbasso/awesome-wasm/blob/master/CONTRIBUTING.md).

Added WASM-PDF to Others list

---

README.md

[go-web-app](https://github.com/talentlessguy/go-web-app) – CLI for quickly bootstrapping Go + WASM frontend apps.

Added go-web-app

---

README.md

Include 2 standard community links for compiling to WASM from Rust.
https://github.com/mbasso/awesome-wasm

add rust WASM links

---

README.md

VuGo This is a WebAssembly Vue.js wrapper written in Go

go: add VueGo to the Golang list

---

README.md

Manticore (https://github.com/trailofbits/manticore) is a symbolic execution engine written in Python that can symbolically evaluate WebAssembly functions. That means that it can call a WebAssembly function with a symbolic value and determine all the possible outputs of that function, including deriving the concrete inputs that produce each output. 
I've written a blog post with more information about WASM support in Manticore here: https://blog.trailofbits.com/2020/01/31/symbolically-executing-webassembly-in-manticore/

Add Manticore

---

README.md

Source code: https://github.com/XD-DENG/handytools-go-webassembly
demo: https://handytools.xd-deng.com/

Add HandyTools as A Go+wasm Example

---

README.md

Vecty lets you build responsive and dynamic web frontends in Go using WebAssembly, competing with modern web frameworks like React & VueJS.
Repository: https://github.com/hexops/vecty
Disclaimer: I am the author of Vecty - I saw this page was linked from https://github.com/golang/go/wiki/WebAssembly#other-webassembly-resources and Vecty is fairly popular (~2k stars) so I figured I would contribute it. Not sure if that's allowed, feel free to close if not.

Add Vecty, a Go web framework

---

README.md

Added a tutorial link to an article that shows two ways to use an import statement with an Emscripten-generated module in Vue.js.

Tutorial link for article about importing a module in Vue.js

---

README.md

Added the "WebAssembly threads in Firefox" article to the Tutorials section. This article shows you how to extend Python's Simple HTTP Server in order to return the necessary response headers to enable the SharedArrayBuffer in Firefox (these headers will become the norm in all browsers in the near future). The article then shows how to use WebAssembly threads to convert a user-supplied image to greyscale.

Added the "WebAssembly threads in Firefox" article.

---

README.md

This benchmark can be run in [browser](https://originjs.org/WASM-benchmark/) or [nodejs](https://github.com/originjs/WASM-benchmark)

Add a new js vs wasm benchmark running in browser/nodejs

---

README.md

Update the descript about WebAssembly-Micro-Runtime (WAMR), which not only
supports interpreter, but also supports AOT/JIT.

Update description about WAMR

---

README.md

We compile our [scientific fluid code Aphros](https://github.com/cselab/aphros) as a WebAssembly library and made [a demo](https://cselab.github.io/aphros/wasm/hydro.html).

demos: add aphros (finite volume solver)

---

README.md

https://github.com/sola-st/WasmBench
WasmBench is a large dataset of more than 8400 real-world WebAssembly binaries, collected from live websites, GitHub, NPM packages, browser extensions, and more sources. The dataset is useful, e.g., for testing WebAssembly-related tools, as training data for machine learning, and because of the insights how WebAssembly is used in practice (e.g., from which source languages Wasm binaries are commonly compiled, what imports they use, how large they are, etc.) The dataset is described in more detail in [a paper published at _The Web Conference 2021_](https://dlehmann.eu/publications/WasmBench-www2021.pdf), which goes into more detail of the methodology for collecting the binaries and our statistical evaluation.

Add WasmBench dataset and paper

---

README.md

Add another way to build cpython for webassembly.

add python-wasm

---

README.md

See https://github.com/eunomia-bpf/wasm-bpf.
`Wasm-bpf` is a WebAssembly eBPF library, toolchain and runtime powered by CO-RE (Compile Once – Run Everywhere) libbpf and WAMR. It can help you build almost every eBPF programs or use cases to Wasm.

Add wasm-bpf: Wasm library and toolchain for eBPF

---

README.md

Pyodide linked to PyScript github and PyScript linked to Pyodide github. 
Swapped Pyodide and PyScript links url with each other.

Fix Pyodide and PyScript links

---

README.md

Adding Ruffle, an Adobe Flash Player emulator written in the Rust, it targets both the desktop and the web using WebAssembly.
- [+ ] I've read [CONTRIBUTING.md](https://github.com/mbasso/awesome-wasm/blob/master/CONTRIBUTING.md).
- [ +] Description explains the issue / use-case resolved, and auto-closes the related issue(s) (https://help.github.com/articles/closing-issues-via-commit-messages/).

Adding Ruffle

---

README.md

add OCaml related tools (Wasocaml and Owi)
